### ISSUE TITLE
JobDataMap of trigger is empty

### ISSUE THREAD

**Issue by aleh-lapin** [michaelklishin/quartz-mongodb#103]
I create a trigger:
CronTrigger trigger = newTrigger()
				.withIdentity("my_trg" + settings.getDashboardId(), "my_group")
				.usingJobData("id", settings.getId())
				.usingJobData("message", settings.getMessage())
				.usingJobData("notify", settings.isNotify())
				.usingJobData("notify2", settings.isNotify2())
				.withSchedule(cronSchedule(settings.getCronExpression()))
				.startAt(settings.getStartDate())
				.build();

in  execute(JobExecutionContext context) method of my job merdedJobDataMap comes empty.		
		JobDataMap dataMap = context.getMergedJobDataMap();

If i'm trying to get job data map of trigger like
Trigger trigger  = scheduler.getTrigger(getTriggerKey(dashboardId));
it comes empty too.

**Comment by pwojnowski** [comment]
Good catch. Thanks! :+1:
