### ISSUE TITLE
Revert deprecation of MongoDBJobStore.overrideMongo

### ISSUE THREAD

**Issue by BenRomberg** [michaelklishin/quartz-mongodb#105]
We've implemented a way to override the Mongo Client with #77. I wonder why this is marked as deprecated now? Is there another way to override the Mongo Client in a test environment?

**Comment by michaelklishin** [comment]
@BenRomberg see https://github.com/michaelklishin/quartz-mongodb/commit/9fee3bb43bb1a8e92c09791432a0e0ca1d33b02a.

**Comment by BenRomberg** [comment]
Thanks. So I guess the proposed strategy is to extend `MongoDBJobStore` and provide the Mongo instance within the call to the super-constructor, and use that class as the `org.quartz.jobStore.class`.

**Comment by michaelklishin** [comment]
To use the newly introduced constructor any way you need, correct.
