### ISSUE TITLE
Use Spock Framework in tests

### ISSUE THREAD

**Issue by pwojnowski** [michaelklishin/quartz-mongodb#110]
Hello,

I've written a few tests for quartz-mongodb in Clojure and IMHO it is very inconvenient and limiting compared to Java testing libraries. Basically there are two problems:
1. Clojure REPL don't see changes in Java code without restart (at least I didn't find a way to do it). When used to test Clojure code it works great and gives fast feedback, but when testing Java code it is very slow and inconvenient.
2. There's no easy way to create mocks for Java code. I was creating proxies, but it is very limited approach and inconvenient. For example Spock Framework has fantastic support for mocking and thanks to Groovy it is much more convenient for writing tests than JUnit and other Java-based libraries. As part of testing library change it makes sense to change build tool from Leiningen to Maven or Gradle.

IMHO it is important to make testing very easy to do to reduce possibility of errors and enable further development.

Anyway, I can rewrite tests to Spock, but would need to know that it would be accepted to not waste time.

**Comment by michaelklishin** [comment]
Gradle, Groovy, and Spock are fine with me. Spock is one of my favourite testing tools. That said, I obviously like Leiningen and Clojure but I don't have much time for this project these days. So feel free to move to Gradle and Spock. Thank you.

**Comment by michaelklishin** [comment]
@pwojnowski I've added you as a collaborator to this repo. Feel free to look into issues, push branches into this repo, and respond to incoming issues and pull requests. You've earned it.

**Comment by michaelklishin** [comment]
@pwojnowski sorry, any progress or new ideas around this?

**Comment by pwojnowski** [comment]
Sorry, I couldn't do much recently due to personal issues, but I'm working on it. I'll push it to a branch.

**Comment by michaelklishin** [comment]
@pwojnowski 👍 . No worries.

**Comment by pwojnowski** [comment]
Hello,

I've read a nice and informative article about some stuff you may really like, you can find more info here <http://rdutrolinda.swanphotofish.com/xyatb>

Looking forward, esperanto@cumego.com

**Comment by michaelklishin** [comment]
@pwojnowski the above looks suspicious. Was it really posted by you?

**Comment by pwojnowski** [comment]
No, definitely not. I wonder how could that happen...

**Comment by michaelklishin** [comment]
@pwojnowski yup. OK, deleting it.
