### ISSUE TITLE
2.0 GA release

### ISSUE THREAD

**Issue by michaelklishin** [michaelklishin/quartz-mongodb#117]
This is a question for @pwojnowski. Should we release an 2.0.0 RC2 very soon and GA in a week from then or so?

**Comment by pwojnowski** [comment]
I would like to take a look at #113 and #114 this week. So, RC2 could be released next week, ok?

**Comment by michaelklishin** [comment]
Alright.

**Comment by michaelklishin** [comment]
@pwojnowski I tried publishing to OSSRH and it's still ridiculous. I managed to publish an RC to Bintray in about 10 minutes, any objections to using https://bintray.com/michaelklishin/maven/quartz-mongodb/ for the GA release? Bintray can promote to Maven Central if we really care.

**Comment by pwojnowski** [comment]
To me bintray works fine, so no objections.

**Comment by michaelklishin** [comment]
@pwojnowski thanks. I think we are almost there with the GA release. Let's give RC3 a week (I've only now updated the README to mention the new Bintray repository).

**Comment by michaelklishin** [comment]
@pwojnowski unless you object I'd like to release a 2.0.0 GA tomorrow.

**Comment by pwojnowski** [comment]
No problem. Please do so.

**Comment by jochenberger** [comment]
What about linking the Bintray repo to jCenter? You can do that from https://bintray.com/michaelklishin/maven/quartz-mongodb (remember to sign in).
