### ISSUE TITLE
Incompatible with quartz 2.2.3

### ISSUE THREAD

**Issue by dorogush** [michaelklishin/quartz-mongodb#118]
Quartz 2.2.3 `org.quartz.spi.JobStore` has slightly different method signatures compared to `com.novemberain.quartz.mongodb.MongoDBJobStore`

**Comment by spdaley** [comment]
Just curious but are there any plans on fixing this before GA? From the other issues, it looks like a GA is imminent.

**Comment by michaelklishin** [comment]
2.0 GA is at least one more RC away. @pwojnowski WDYT about delaying until this is resolved?

@spdaley feel free to look into a pull request, this is open source software after all ;)

**Comment by pwojnowski** [comment]
It is fine for me.
