### ISSUE TITLE
about mongo-java-driver

### ISSUE THREAD

**Issue by balajinima** [michaelklishin/quartz-mongodb#122]
hi ,I am confused with mongodb-driver and mongo-java-driver, what is the differences, spring-boot-starter-data-mongodb use  mongodb-driver .  if i use quartz-mongodb can i depand it ?

**Comment by pwojnowski** [comment]
According to [mongo-java-driver#binaries](https://github.com/mongodb/mongo-java-driver#binaries) mongo-java-driver contains core driver (mongodb-driver) and BSON classes - quartz-mongodb is using both.

IMHO if they are in the same versions then there should be no problem.

**Comment by balajinima** [comment]
thanks a lot
