### ISSUE TITLE
Grails 3 

### ISSUE THREAD

**Issue by yoann-trouillet** [michaelklishin/quartz-mongodb#130]
Hi Michael,

I have been reading this post http://blog.klarshift.de/2015/05/23/use-mongodb-as-storage-for-your-quartz2-in-grails/ 

I was wondering if you know of any issues or examples using mongodb backed quartz with Grails 3.1.X (Quartz is baked in Grails 3)

Thanks for your time.

**Comment by michaelklishin** [comment]
I'm not aware of any examples but also don't think there'd be anything Grails-specific. Just use this Quartz plugin as you would in any other JVM-based project.
