### ISSUE TITLE
Please link Bintray repository to JCenter

### ISSUE THREAD

**Issue by jochenberger** [michaelklishin/quartz-mongodb#132]
For 2.0 and newer releases to be available from JCenter, the Bintray repo should be linked with it. You can do that from https://bintray.com/michaelklishin/maven/quartz-mongodb (remember to sign in).

**Comment by korest** [comment]
Not sure why but it's not working for me to resolve dependency from bintray

**Comment by michaelklishin** [comment]
I've linked it with group `com.novemberain` but it still doesn't appear in the list of linked repositories. Let's give it some time.

**Comment by michaelklishin** [comment]
OK, so apparently the "Add to JCenter" button leads me to a message composer, so that's just placing a request. We should wait then.

**Comment by jochenberger** [comment]
Didn't you get a response yet? They usually reply within a day.

**Comment by michaelklishin** [comment]
They did. I need to include source and JavaDoc packages in order to be accepted. I'm not a Gradle expert so if you know what's the right way to do that, feel free to look into a PR and I will try again :)

**Comment by jochenberger** [comment]
Hm, source JARs are what I tried to accomplish with #123. I don't think that you need a JavaDoc JAR if you have a source JAR. I have various projects linked to JCenter that only have source JARs.
In fact, `gradle build` builds the source JAR just fine. How do you upload your packages to Bintray?

**Comment by jochenberger** [comment]
Ah, you use the `bintrayUpload` task, as I do. But you configure a `publication` (https://github.com/michaelklishin/quartz-mongodb/blob/master/build.gradle#L114) and I configure a *`configuration`* (https://github.com/eddyson-de/tapestry-react/blob/master/build.gradle#L147).
It's probably just a matter of adding the source JAR artiifact to the "QuartzMongoDB" publication. I wonder what the difference is.

**Comment by jochenberger** [comment]
You may have to upload the 2.0.0 source JAR manually to BinTray.

**Comment by michaelklishin** [comment]
Yup. Will give that a shot later, thank you.

**Comment by jochenberger** [comment]
You're welcome.

**Comment by jochenberger** [comment]
Any news?

**Comment by jochenberger** [comment]
@michaelklishin, any news?

**Comment by michaelklishin** [comment]
I tried linking the repo on Bintray again, still no effect after a few days and absolutely no errors or notifications of any kind.

**Comment by michaelklishin** [comment]
Got a response from Bintray, investigating what else has to happen (we seem to include a source jar and now a javadoc one).

**Comment by michaelklishin** [comment]
According to the [package page](https://bintray.com/beta/#/michaelklishin/maven/quartz-mongodb?tab=overview), this artifact is included into JCenter now.
