### ISSUE TITLE
schedule a job every 100 millisecond but actually running every 30 sec

### ISSUE THREAD

**Issue by hemau23** [michaelklishin/quartz-mongodb#134]
I tried to create a trigger which should run every 100 mili sec but in actual teh job is geting triggered after every 30 sec or more. 

newTrigger()
                .forJob(jobDetail)
                .withIdentity(jobDetail.getKey().getName() + TRIGGER, jobDetail.getKey().getName() + GROUP)
                .withSchedule(SimpleScheduleBuilder
                        .repeatSecondlyForever()
                                      .simpleSchedule()
                                      .withIntervalInMilliseconds(100)
                                      .repeatForever())            
                .build();

am I doing something wrong in above code.  ?

**Comment by michaelklishin** [comment]
Scheduling is not performed by Quartz store. You use `repeatSecondlyForever` combined with an interval. Aren't those things conflicting? Anyhow, it's a question for the Quartz mailing list.

**Comment by hemau23** [comment]
sorry I was working on that and 
newTrigger()
                .forJob(jobDetail)
                .withIdentity(jobDetail.getKey().getName() + TRIGGER, jobDetail.getKey().getName() + GROUP)
                .withSchedule(SimpleScheduleBuilder
                                      .simpleSchedule()
                                      .withIntervalInMilliseconds(100)
                                      .repeatForever())            
                .build();

this is what my actual code
