### ISSUE TITLE
JobData added to Trigger not passed to Job Instance

### ISSUE THREAD

**Issue by zeeshan-v1** [michaelklishin/quartz-mongodb#143]
http://stackoverflow.com/q/42025607/3148412

I have a durable job added to the scheduler. At the runtime, i am building a trigger using below code:

```
Trigger trigger = TriggerBuilder.newTrigger()
                    .withIdentity(new TriggerKey(triggerKey))
                    .forJob(Constants.CAMPAIGN_MAILING_JOB_KEY)
                    .usingJobData("test", "test")
                    .startAt(new Date(runTime))
                    .build();
```
I then schedule this job using ,

`scheduler.scheduleJob(trigger);`
The job is executed properly, however the Jobdata ("test" string param) is giving me null in the job. this is my job code,

```
public class CampaignMessageSendingJob implements Job{
public String campaignId;
public String messageId;

@Override
public void execute(JobExecutionContext jobContext) throws JobExecutionException {
    System.out.println("This JOb Was called at"+System.currentTimeMillis());

    JobKey key = jobContext.getJobDetail().getKey();
    JobDataMap map= jobContext.getMergedJobDataMap();
    System.out.println(map.getString("test")); //This is printing NULL

}

public String getCampaignId() {
    return campaignId;
}

public void setCampaignId(String campaignId) {
    this.campaignId = campaignId;
}

public String getMessageId() {
    return messageId;
}

public void setMessageId(String messageId) {
    this.messageId = messageId;
}
}
```

**Comment by michaelklishin** [comment]
Can this be reproduced with another Quartz store? So far there is no evidence that it is an issue in the store.

**Comment by zeeshan-v1** [comment]
I havent checked with Quartz RamJobStore yet, will do and update. One thing i wanted to mention is i havent added below line in props- is that going to cause an issue?
`org.quartz.jobStore.jobDataAsBase64=false`

**Comment by zeeshan-v1** [comment]
I also tried the Job with Non-Durability as well, the issue persists. Whatever i add with usingJobData on Trigger is not being transferred to Job Instance

**Comment by zeeshan-v1** [comment]
@michaelklishin  i verified this.. with Ram Store its working perfectly fine.  However as i add ,mongodb store, the trigger Job data becomes null.
Here is my quartz property file and i am unsing quartz-mongodb-2.0.0-rc.jar
# Use the MongoDB store 
org.quartz.jobStore.class=com.novemberain.quartz.mongodb.MongoDBJobStore
# MongoDB URI (optional if 'org.quartz.jobStore.addresses' is set)
org.quartz.jobStore.mongoUri=mongodb://localhost:27017
# comma separated list of mongodb hosts/replica set seeds (optional if 'org.quartz.jobStore.mongoUri' is set)
#org.quartz.jobStore.addresses=host1,host2
# database name
org.quartz.jobStore.dbName=mailemergencydb2

# Will be used to create collections like mycol_jobs, mycol_triggers, mycol_calendars, mycol_locks
org.quartz.jobStore.collectionPrefix=mailemergency
# thread count setting is ignored by the MongoDB store but Quartz requries it
org.quartz.threadPool.threadCount=1
org.quartz.scheduler.instanceName = MailEmergencyJobScheduler
#this should be true in production 
org.quartz.scheduler.skipUpdateCheck=true

**Comment by zeeshan-v1** [comment]
FIXED by using correct version of Jar.
I was using quartz-mongodb-2.0.0-rc2.jar where as i should have been using quartz-mongodb-2.0.0.jar
