### ISSUE TITLE
Unable to serialize JobDataMap for insertion into database because the value of property 'methodInvoker' is not serializable: org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean

### ISSUE THREAD

**Issue by wqe146273123** [michaelklishin/quartz-mongodb#145]
use spring boot  quartz 2.2.3  quartz-mongodb but appear：Unable to serialize JobDataMap for insertion into database because the value of property 'methodInvoker' is not serializable: org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean 

this is my config class:
@Bean("schedulerFactory")
	public SchedulerFactoryBean schedulerFactoryBean() {
		SchedulerFactoryBean schedulerFactory = new SchedulerFactoryBean();
		Resource resource = new ClassPathResource("jobstore.properties");
		schedulerFactory.setConfigLocation(resource);
		
		MethodInvokingJobDetailFactoryBean JobDetailFactory = new MethodInvokingJobDetailFactoryBean();
		JobDetailFactory.setName("test");
		JobDetailFactory.setTargetObject(app.getbean("testJob"));
		JobDetailFactory.setTargetMethod("work");
		JobDetailFactory.setConcurrent(false);
		try {
			JobDetailFactory.afterPropertiesSet();
		} catch (ClassNotFoundException | NoSuchMethodException e1) {
			e1.printStackTrace();
		}
		JobDetail jobDetail = JobDetailFactory.getObject();
		
		CronTriggerFactoryBean cronTriggerFactoryBean  = new CronTriggerFactoryBean ();
		cronTriggerFactoryBean.setJobDetail(jobDetail);
		cronTriggerFactoryBean.setCronExpression("0/20 * * * * ?");
		cronTriggerFactoryBean.setName("test");
		try {
			cronTriggerFactoryBean.afterPropertiesSet();
		} catch (ParseException e) {
			e.printStackTrace();
		}
		CronTrigger cronTrigger = cronTriggerFactoryBean.getObject();
		schedulerFactory.setTriggers(cronTrigger);
		return schedulerFactory;
	}

**Comment by michaelklishin** [comment]
Quartz stores assume that the job context map they are given can be serialised.

**Comment by lxwhappy** [comment]
hello，i am have the same exception，finally，how solved？

**Comment by michaelklishin** [comment]
> Quartz stores assume that the job context map they are given can be serialised.

so you can only use values that can be serialised (as in Java's built-in serialisation) in job context maps.
