### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: org/bson/conversions/Bson

### ISSUE THREAD

**Issue by ManinderHSC** [michaelklishin/quartz-mongodb#148]
Getting below exception 

Caused by: java.lang.NoClassDefFoundError: org/bson/conversions/Bson
	at com.novemberain.quartz.mongodb.MongoStoreAssembler.<init>(MongoStoreAssembler.java:42)
	at com.novemberain.quartz.mongodb.MongoDBJobStore.<init>(MongoDBJobStore.java:28)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:869)
	at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1519)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.createScheduler(SchedulerFactoryBean.java:597)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.afterPropertiesSet(SchedulerFactoryBean.java:480)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 56 more
Caused by: java.lang.ClassNotFoundException: org.bson.conversions.Bson

	<properties>
		<java.source.version>1.8</java.source.version>
		<maven.compile.version>3.3</maven.compile.version>
		<spring.version>4.2.5.RELEASE</spring.version>
		<spring.ldap.version>1.3.1.RELEASE</spring.ldap.version>
		<spring.security.version>3.2.5.RELEASE</spring.security.version>
		<spring.oauth.version>2.0.5.RELEASE</spring.oauth.version>
		<servlet.api.version>3.0.1</servlet.api.version>
		<commons.io.version>1.3.2</commons.io.version>
		<commons.dbcp.version>1.4</commons.dbcp.version>
		<org.json.version>20090211</org.json.version>
		<json.schema.version>2.2.6</json.schema.version>
		<log4j.version>2.6.1</log4j.version>
		<quartz.version>2.2.1</quartz.version>
		<jboss.jms.client.version>7.2.0.Final</jboss.jms.client.version>
		<jboss.jms.api.version>1.1.0.GA</jboss.jms.api.version>
		<jboss.jnpserver.version>5.0.3.GA</jboss.jnpserver.version>
		<netty.version>4.0.36.Final</netty.version>
		<hornetq.version>2.4.0.Final</hornetq.version>
		<slf4jVersion>1.6.1</slf4jVersion>
		<aspectj.version>1.8.7</aspectj.version>
		<mongodb.version>1.9.2.RELEASE</mongodb.version>
		<apache.poi.version>3.14</apache.poi.version>
		<opencsv.version>3.8</opencsv.version>
		<protobuf.java.version>3.0.2</protobuf.java.version>
		<protobuf.version>1.0.0</protobuf.version>
		<jackson.version>2.4.1</jackson.version>
		<google.gson.version>2.2.2</google.gson.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<wildfly.version>9.0.2.Final</wildfly.version>
	</properties>

<dependencies>
		
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-tx</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-orm</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aop</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-support</artifactId>
			<version>${spring.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-web</artifactId>
			<version>${spring.security.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-config</artifactId>
			<version>${spring.security.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security.oauth</groupId>
			<artifactId>spring-security-oauth2</artifactId>
			<version>${spring.oauth.version}</version>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>${servlet.api.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>${google.gson.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson.version}</version>
		</dependency>
		<dependency>
			<groupId>commons-dbcp</groupId>
			<artifactId>commons-dbcp</artifactId>
			<version>${commons.dbcp.version}</version>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>${org.json.version}</version>
		</dependency>
		<dependency>
			<groupId>com.github.fge</groupId>
			<artifactId>json-schema-validator</artifactId>
			<version>${json.schema.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.ldap</groupId>
			<artifactId>spring-ldap-core</artifactId>
			<version>${spring.ldap.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.ldap</groupId>
			<artifactId>spring-ldap-core-tiger</artifactId>
			<version>${spring.ldap.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.ldap</groupId>
			<artifactId>spring-ldap-odm</artifactId>
			<version>${spring.ldap.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.ldap</groupId>
			<artifactId>spring-ldap-ldif-core</artifactId>
			<version>${spring.ldap.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.ldap</groupId>
			<artifactId>spring-ldap-ldif-batch</artifactId>
			<version>${spring.ldap.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>${log4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>${log4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-io</artifactId>
			<version>${commons.io.version}</version>
		</dependency>
		<dependency>
			<groupId>org.hornetq</groupId>
			<artifactId>hornetq-core-client</artifactId>
			<version>${hornetq.version}</version>
		</dependency>
		<dependency>
			<groupId>org.hornetq</groupId>
			<artifactId>hornetq-server</artifactId>
			<version>${hornetq.version}</version>
		</dependency>
		<dependency>
			<groupId>org.hornetq</groupId>
			<artifactId>hornetq-jms-client</artifactId>
			<version>${hornetq.version}</version>
		</dependency>
		<dependency>
			<groupId>org.hornetq</groupId>
			<artifactId>hornetq-jms-server</artifactId>
			<version>${hornetq.version}</version>
		</dependency>
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-all</artifactId>
			<version>${netty.version}</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.javaee</groupId>
			<artifactId>jboss-jms-api</artifactId>
			<version>${jboss.jms.api.version}</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.naming</groupId>
			<artifactId>jnpserver</artifactId>
			<version>${jboss.jnpserver.version}</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.as</groupId>
			<artifactId>jboss-as-jms-client-bom</artifactId>
			<version>${jboss.jms.client.version}</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjrt</artifactId>
			<version>${aspectj.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjtools</artifactId>
			<version>${aspectj.version}</version>
		</dependency>

		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjweaver</artifactId>
			<version>${aspectj.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${slf4jVersion}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-mongodb</artifactId>
			<version>${mongodb.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>${apache.poi.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>${apache.poi.version}</version>
		</dependency>
		<dependency>
			<groupId>com.opencsv</groupId>
			<artifactId>opencsv</artifactId>
			<version>${opencsv.version}</version>
		</dependency>
		<dependency>
			<groupId>org.quartz-scheduler</groupId>
			<artifactId>quartz</artifactId>
			<version>${quartz.version}</version>
		</dependency>
	<dependency>
		<groupId>org.quartz-scheduler</groupId>
		<artifactId>quartz-jobs</artifactId>
		<version>${quartz.version}</version>
	</dependency>
	<dependency>
		<groupId>com.google.protobuf</groupId>
		<artifactId>protobuf-java</artifactId>
		<version>${protobuf.java.version}</version>
	</dependency>
	<dependency>
		<groupId>commons-fileupload</groupId>
		<artifactId>commons-fileupload</artifactId>
		<version>1.3.2</version>
	</dependency>

	<dependency>
		<groupId>com.jcraft</groupId>
		<artifactId>jsch</artifactId>
		<version>0.1.54</version>
	</dependency>
	
	<dependency>
	    <groupId>org.reflections</groupId>
	    <artifactId>reflections</artifactId>
	    <version>0.9.10</version>
	</dependency>
	
	
	<dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-compress</artifactId>
		<version>1.1</version>
	</dependency>
	<dependency>
		<groupId>org.wildfly</groupId>
		<artifactId>wildfly-clustering-infinispan-extension</artifactId>
		<version>${wildfly.version}</version>
		<scope>provided</scope>
		<exclusions>
			<exclusion>
				<groupId>org.jboss.metadata</groupId>
				<artifactId>jboss-metadata-common</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.jboss.metadata</groupId>
				<artifactId>jboss-metadata-ejb</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.jboss.metadata</groupId>
				<artifactId>jboss-metadata-ear</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.jboss.openjdk-orb</groupId>
				<artifactId>openjdk-orb</artifactId>
			</exclusion>
		</exclusions>
	</dependency>

		
		<dependency>
			<groupId>org.snmp4j</groupId>
			<artifactId>snmp4j</artifactId>
			<version>2.5.3</version>
		</dependency>
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>1.1.0.Final</version>
		</dependency>
		<dependency>
    <groupId>com.novemberain</groupId>
    <artifactId>quartz-mongodb</artifactId>
    <version>2.0.0</version>
      <exclusions>
        <exclusion>  
          <groupId>org.mongodb</groupId>
          <artifactId>mongodb-driver</artifactId>
         
        </exclusion>
             <exclusion>  
          <groupId>org.quartz-scheduler</groupId>
          <artifactId>quartz</artifactId>
         
        </exclusion>
      </exclusions> 
</dependency>

**Comment by michaelklishin** [comment]
One of the MongoDB driver dependencies is not satisfied. Sorry, I don't have the time to answer such questions, please figure it out on your own.

**Comment by pwojnowski** [comment]
MongoDB 1.9 is not supported. You'll need at least 2.6 (preferably never) to use quartz-mongodb.
