### ISSUE TITLE
Difference between isClustered

### ISSUE THREAD

**Issue by korest** [michaelklishin/quartz-mongodb#149]
Small questions regarding clustered mode.
I have few jobs that are running and I'm using your library and I want to know if there any difference between running in clustered mode or not in case of parallel jobs execution.

As I can see if two server start the same job one will insert lock to the database and execute job and other one will fail to insert lock so will not execute the same job is is correct?

What problems can solve clustered mode?
Thanks for info.

Also small improvement. In documentation you have section "Different time settings for cluster operations:" and all values have prefix "org.quartz.scheduler" but probably it should be "org.quartz.jobStore".

**Comment by michaelklishin** [comment]
This is a general [Quartz clustering](http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/tutorial-lesson-11.html) question, there is nothing specific to MongoDB.

Clustered mode means you don't depend on a single node. It can improve parallelism as a side effect but the idea first and foremost to run more than one node to improve availability.

**Comment by korest** [comment]
@michaelklishin Ok thank you! Will you update the section with time settings properties as I wrote or should I create a PR for that?

**Comment by michaelklishin** [comment]
@korest feel free to submit a PR. Thank you!
