### ISSUE TITLE
Error retrieving job for trigger

### ISSUE THREAD

**Issue by tomekl007** [michaelklishin/quartz-mongodb#153]
We get a lot of:
Error retrieving job for trigger xxx, setting trigger state to ERROR.
We are trying to understand why this is happening.

**Comment by george-harness** [comment]
We having the same issue. Did you find the reason?

**Comment by michaelklishin** [comment]
We cannot suggest anything with the amount of information provided. Enable extended logging, including for MongoDB Java client, and see what is logged.
