### ISSUE TITLE
DailyTimeIntervalTriggerPropertiesConverter lost days of week

### ISSUE THREAD

**Issue by 94047764** [michaelklishin/quartz-mongodb#155]
DailyTimeIntervalTriggerImpl.setDaysOfWeek

but, DailyTimeIntervalTriggerPropertiesConverter  unsupport this property.

**Comment by michaelklishin** [comment]
If someone understands what's reported here and what should be done instead, please submit a PR.

**Comment by michaelklishin** [comment]
This was followed-up to in #189.
