### ISSUE TITLE
one of mongo node shutdown, will trigger jvm exit.

### ISSUE THREAD

**Issue by 94047764** [michaelklishin/quartz-mongodb#156]
when one of mongo node shutdown, 
CheckinTask will catch MongoException, then do System.exit(1);
In fact, one of mongo node shutdown, but the hole mongo cluster can continue work.

**Comment by michaelklishin** [comment]
https://github.com/michaelklishin/quartz-mongodb/commit/116546623734455191611822b23abe7c8740453f explains why. This is not great but it's not obvious what should be done (e.g. how to stop just Quartz itself) in clustered setups.

**Comment by michaelklishin** [comment]
Actually, there's already an issue about this, #147.
