### ISSUE TITLE
Quartz 2.3.0

### ISSUE THREAD

**Issue by lazystone** [michaelklishin/quartz-mongodb#157]
The latest quartz is 2.3.0, however I can't find release notes.

It seems that they added two new methods to JobStore in the 2.3.0:
* resetTriggerFromErrorState
* getAcquireRetryDelay

So it's not just a version bump.

**Comment by Chevron94** [comment]
Please review implementation for this issue https://github.com/michaelklishin/quartz-mongodb/pull/178
