### ISSUE TITLE
How to share Mongo database instance with MongoDBStore?

### ISSUE THREAD

**Issue by titogarcia** [michaelklishin/quartz-mongodb#165]
The easiest and safest way I have found is to define my own extension of MongoDBStore, taking the database instance from a static field:
```
  public static class MyMongoDBJobStore extends MongoDBJobStore {
    public MyMongoDBJobStore() {
      super(Mongo.database);
    }
  }
```

Then setting `org.quartz.jobStore.class` to this class.

Is there a different recommended way?

Thanks

**Comment by michaelklishin** [comment]
Unless you start Quartz and configure it using Java code, I don't think this is something that this project supports.
