### ISSUE TITLE
When do you have plans to release this version?

### ISSUE THREAD

**Issue by gurubelli** [michaelklishin/quartz-mongodb#166]
Hi
Can you please let us know when are you going to release new version?

**Comment by srinivaswings** [comment]
Could please release the version?. We want to use this in our production environment.

**Comment by ikv163** [comment]
Hello,
I'm also interested in new version. Are you planning to release it in the nearest future?

**Comment by michaelklishin** [comment]
As soon as I finish some refactoring/safety improvements around https://github.com/michaelklishin/quartz-mongodb/issues/163. There is no ETA.

**Comment by max3163** [comment]
4 months without move on the git, do you plan to release asap ?

**Comment by chefkoch333** [comment]
Also looking for a relase to use org.quartz.jobStore.checkInErrorHandler.class property which is apparently not available in 2.1.0.

**Comment by RobWin** [comment]
We are also interested in the latest changes.

**Comment by max3163** [comment]
Is this project is dead ?

**Comment by michaelklishin** [comment]
@max3163 it could use a maintainer that actually uses it and is more familiar with Quartz than I am after about 7 years of not touching it much. Are you interested in becoming a maintainer?

Meanwhile, [2.2.0-rc1 is up on Bintray](https://bintray.com/beta/#/michaelklishin/maven/quartz-mongodb/2.2.0-rc1?tab=overview)

**Comment by srinivaswings** [comment]
Can you please add me as maintainer?

**Comment by michaelklishin** [comment]
@srinivaswings invite sent.
