### ISSUE TITLE
Unnecessary info logging every second

### ISSUE THREAD

**Issue by harishvashistha** [michaelklishin/quartz-mongodb#167]
This prints every second in info logs even when I want to run this job in one day interval
Node {}:{} checks-in.
Found {} triggers which are eligible to be run.

can this logging level be made debug? otherwise it is filling up the log space pretty soon.

**Comment by mariusleu** [comment]
+1

**Comment by michaelklishin** [comment]
You haven't provided any examples but those messages are almost certainly logged by core Quartz. Please submit a PR (change the level to `debug` if I'm wrong).
