### ISSUE TITLE
Updating data to trigger collection to mongodb sometimes fails

### ISSUE THREAD

**Issue by xucong996** [michaelklishin/quartz-mongodb#172]
we uesd custer mongodb, and all of collection in the db is sharded by _id, but the trigger collection created with unique inex(keyGroup_1_keyName_1), so we only created trigger collection not use shard.   sometimes, we use storeTriggerAndJob(),  jobDao will Working normally， but triggerDao will get a exception, :
`com.mongodb.MongoBulkWriteException : Bulk write operation error on server 12.10.13.15.16852. Write concern error : WriteConcernError{code=64. codeName='', message='waiting for replication timed out at shardll''}`

**Comment by michaelklishin** [comment]
> waiting for replication timed out at shardll

is the line you are looking for. This job store cannot avoid timeouts of MongoDB operations. Operation timeouts is a sad fact of distributed systems life. If you have specific suggestions as to what this job could do better to be more resilient, please submit a pull request.
