### ISSUE TITLE
Add Support For Useing With Spring Boot

### ISSUE THREAD

**Issue by ankurpathak** [michaelklishin/quartz-mongodb#175]
Pls add support for useing with Spring Boot. Or Provide a sample applicaton showing Support For MongoDB

**Comment by michaelklishin** [comment]
I think "support for MongoDB" has been explained in the README since day one. I don't have the cycles to produce example apps. If someone would be interested in contributing, please release it under your own GitHub account and perhaps submit a README PR with a link.
