### ISSUE TITLE
Can we have Proper Release Schedule and Dependency Updates

### ISSUE THREAD

**Issue by ankurpathak** [michaelklishin/quartz-mongodb#177]
I have railsed a issue for adding Quartz Mongo Job Store by this project to Spring Boot Starter Quartz. The team of Spring Boot was ready to consider this project, but they closed it because
of not keeping with latest dependencies. So can we have proper release cycle and dependency
update for this Project. So that we can have inbuild integration for this project in Spring Boot.
https://github.com/spring-projects/spring-boot/issues/17849

**Comment by michaelklishin** [comment]
@ankurpathak this is open source software. The way you achieve "proper release cycle and dependency updates" is by contributing, not telling others to do it.

I have just released a `2.2.0-rc1` with MongoDB Java driver 4 as a dependency.
