### ISSUE TITLE
Inaccurate scheduling based on seconds

### ISSUE THREAD

**Issue by jasonhuxinlei** [michaelklishin/quartz-mongodb#182]
Regardless of whether to use crontrigger for task triggering or simpletrigger for task triggering, when the set task scheduling interval is within 30 seconds, such as scheduling every 5 seconds, the task triggering time is sometimes accurate and sometimes inaccurate.
![image](https://user-images.githubusercontent.com/30133705/72042540-d1644680-32e9-11ea-8809-e6b79ac7bfa1.png)

**Comment by michaelklishin** [comment]
I cannot suggest much with the amount of information provided.
