### ISSUE TITLE
Cannot set triggers with the same trigger name for different tasks under different scheduling instances

### ISSUE THREAD

**Issue by jasonhuxinlei** [michaelklishin/quartz-mongodb#183]
Task 1: The scheduling instance name is testScheduler1
Task 2: The scheduling instance name is testScheduler2
Task names, task group names, trigger names, and trigger group names for task one and task two are the same
Task 1:
![image](https://user-images.githubusercontent.com/30133705/72042966-ec838600-32ea-11ea-8786-4de0c54af611.png)
Task 2:
![image](https://user-images.githubusercontent.com/30133705/72042993-f907de80-32ea-11ea-9045-f771440b612c.png)
I started task one first and saw the normal execution; then I started task two and found that an error occurred
![image](https://user-images.githubusercontent.com/30133705/72043061-281e5000-32eb-11ea-98e5-8c987bb86641.png)

**Comment by michaelklishin** [comment]
I'd consider a PR that makes it possible to support multiple scheduler instances. However, this will be a breaking change as far as the data we store in MongoDB goes, and I don't consider this use case a priority for this or any other job store.
