### ISSUE TITLE
When will the new version 2.2.0 be released?

### ISSUE THREAD

**Issue by pop0505** [michaelklishin/quartz-mongodb#184]
This is a good project, and it brings us a lot of convenience，but it has been a long time since last commit. So, when will the new version 2.2.0 be released? And will this project continue to be maintained?

**Comment by paranoidy** [comment]
@michaelklishin same question here

**Comment by gregRzn** [comment]
@michaelklishin Hello, could you release a version with changes that are already merged? I find custom replica set error handlers particularly useful. Thank you!

**Comment by gregRzn** [comment]
@michaelklishin 
Hello again, I made a pull request and described there a problem that I was facing. Could you please review that and release a new version? 
Thanks for a great job with this lib!

**Comment by michaelklishin** [comment]
[2.2.0-rc1 is up on Bintray](https://bintray.com/beta/#/michaelklishin/maven/quartz-mongodb/2.2.0-rc1?tab=overview)
