### ISSUE TITLE
Doesn't work with Spring Boot 2.3.0 

### ISSUE THREAD

**Issue by yashanet** [michaelklishin/quartz-mongodb#191]
Please update libraries to support MongoDB4+

https://docs.spring.io/spring-data/mongodb/docs/3.0.0.RELEASE/reference/html/#upgrading.2-3

**Comment by Artgit** [comment]
+1 please fix it. I'm unable to upgrade to SB 2.3.0 right now

**Comment by Artgit** [comment]
is there any news?

**Comment by pop0505** [comment]
+1 please

**Comment by philipbel** [comment]
No joy 😞

**Comment by michaelklishin** [comment]
This is open source software, so the way to find joy is not by asking others to do the work but by contributing pull requests.

**Comment by yashanet** [comment]
> This is open source software, so the way to find joy is not by asking others to do the work but by contributing pull requests.

There was pull request. But I cant find now (. Working code are here - https://github.com/fluidsonic/quartz-mongodb

**Comment by michaelklishin** [comment]
[2.2.0-rc1 is up on Bintray](https://bintray.com/beta/#/michaelklishin/maven/quartz-mongodb/2.2.0-rc1?tab=overview) and uses MongoDB Java client `4.0.x`.
