### ISSUE TITLE
Failed to lock trigger

### ISSUE THREAD

**Issue by alfredods** [michaelklishin/quartz-mongodb#197]
Hello,

it seems that the problem is not new.

I define a Job and a Trigger, assign names using timestamps and all possible hints that I read on some forums, but I can not solve the problem using mongoDB as jobStore and the class com.novemberain.quartz.mongodb.MongoDBJobStore. I get the error:

quartz.mongodb.LockManager : Failed to lock trigger MarketPlaceGroup.TraderPortalTrigger1594123818411, reason: WriteError{code=11000, message='E11000 duplicate key error collection: pure-market-places.quartz_locks index: keyGroup_1_keyName_1_type_1 dup key: { keyGroup: "MarketPlaceGroup", keyName: "TraderPortalTrigger1594123818411", type: "t" }', details={}}

What is amazing I begin with a complete empty set of collections. There is no quartz_locks yet, but the problem always appears.

Do you have any idea what is wrong?

Best regards

Alfredo

**Comment by alfredods** [comment]
Hello,

I solve the problem removing the index on mongoDB and creating it again. This is but a very manual solution but at this moment works fine.

Regards

Alfredo

**Comment by michaelklishin** [comment]
Distributed locks are hard. Lock TTL is the only known solution. Pull requests that add support for lock TTL would be considered. Otherwise, there isn't much this tool can do as "breaking locks" is a terrible workaround.
