### ISSUE TITLE
How to remove the mongoDB quartz collection at start or at end on a Spring Boot Application

### ISSUE THREAD

**Issue by alfredods** [michaelklishin/quartz-mongodb#199]
Hello,

I come to the conclusion, that if the quarzt mongodb tables are existing, with data and the spring boot application starts again, the complete scheduling works not correctly.

Everytime when before I start my application I remove the quartz collecions on mongoDB and works correctly. But how to do that automatically? And also how to do that in a cloud environment running this application within a cluster?

I will appreciate some hint.

Regards

Alfredo

**Comment by michaelklishin** [comment]
Instead of deleting the data consider investigating what exactly the root cause is. We cannot suggest anything with the amount of information provided. Obviously you can add an application boot step that wipes all collections used by this tool.
