### ISSUE TITLE
2.2.0-rc2 is not on Bintray

### ISSUE THREAD

**Issue by SebastianLng** [michaelklishin/quartz-mongodb#202]
Hi @michaelklishin,

version 2.2.0-rc2 is currently not on [Bintray](https://bintray.com/michaelklishin/maven/quartz-mongodb). Could you publish it?

Looking at the code, you're publish it manually, right?

Thanks.

**Comment by michaelklishin** [comment]
The version was uploaded but not published. Now Bintray UI is failing to load for me and the Bintray publishing Gradle task seemingly does nothing. I will have to take another look.

**Comment by michaelklishin** [comment]
OK, `2.2.0-rc2` now seems to be [published and indexed](https://bintray.com/beta/#/michaelklishin/maven/quartz-mongodb/2.2.0-rc2?tab=overview).
