### ISSUE TITLE
JobExecutionContext.getPreviousFireTime returns actual execution time

### ISSUE THREAD

**Issue by daniel-h** [michaelklishin/quartz-mongodb#6]
When getting the previous fire time in a Job implementation via JobExecutionContext.getPreviousFireTime() it actually returns the current time of execution.

It seems the previousFireTime is set to early in the process.

I would assume it should be set after the job has been completed,
when the lock is removed, taking the time from the lock entry as previousFireTime?

Best regards,
Daniel

**Comment by qtxo** [comment]
I was bitten by this problem in 2.1.0, tldr DON'T use `trigger.getPreviousFireTime()` use:
`JobExecutionContext.getPreviousFireTime() `
