### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by agherardi** [michaelklishin/quartz-mongodb#66]
Hi,
I need support for Quartz clustering - i.e., N > 1 servers, a repeating job runs exactly on one server for every repetition, possibly on a different server each time - using MongoDB as the datastore.

Are you working on adding support for clustering? Are there any technical issues that make the implementation difficult, or it's just a matter of having the time to write the code?

Thanks!

**Comment by javabrains** [comment]
Hi. I also want clustering support in quartz for mongoDb. Can anyone please guide me what are the implementation logic we are missing in current one for cluster support. 
@agherardi @rliberal could you please let me know if you have found out solution for cluster support requirement.?
@michaelklishin could you please brief me on missing feature?

**Comment by bertramn** [comment]
Interesting thread indeed. I did not yet have a closer look at the JDBC cluster code but I would boldly assume that it just requires the use of the atomic lock for update functionality on the trigger data-set. That can be achieved in MongoDB.

**Comment by maheshbabu1907** [comment]
Is this feature still pending?

**Comment by michaelklishin** [comment]
Not only it is "pending", nobody has clearly laid out a design for it.

**Comment by xiaolongyuan** [comment]
+1

**Comment by pwojnowski** [comment]
Hi. I've been working on this recently ([pwojnowski's fork](https://github.com/pwojnowski/quartz-mongodb)). I had to restructure the code a bit to make any sense of it, sorry. :-)

Clustering consists of two parts: load balancing and failover. It can be enabled by setting the clustering property as in Quartz. Load balancing works. Failover should work, but I haven't tested it thoroughly yet, so if anyone would like to do some testing - feel free. Failover is using approach of lock expiration. Locks have scheduler id and lock time on them and a scheduler finds that lock has expired it assumes that its scheduler is defunct and the lock can be taken over. This means that expiration time option should be higher than longest job execution time. It isn't ideal solution, but at least it works and is good enough for not long jobs.

Current clustering implementation assumes that there is only one cluster per Mongo Collection. For other clusters use different collection name.

@michaelklishin If you are fine with the changes I can create a pull request.

**Comment by michaelklishin** [comment]
@pwojnowski thanks. It would be much easier to reason about the changes if you submit a pull request. Pull requests can be updated by pushing to the same branch ;)

**Comment by pwojnowski** [comment]
There are more than 70 commits, so not sure that PR will help, but will submit.
