### ISSUE TITLE
please support ssl

### ISSUE THREAD

**Issue by hqytchfm** [michaelklishin/quartz-mongodb#80]
I need the quartz-mongodb support ssl,and now I rewrite the source code to support it.but if the version upgrade I need rewrite it to the new version again. so, I suggest that the ssl support will be added at  the next version. Thank you!

**Comment by pwojnowski** [comment]
Hi. Could you try with mongo client uri like so:
http://mongodb.github.io/mongo-java-driver/3.0/driver/reference/connecting/ssl/

IMHO to use that with MongoClientOptions it's enough to add property for enabling SSL and use:
MongoClientOptions.builder().sslEnabled(enableSSL).build()

**Comment by michaelklishin** [comment]
Should be done in master.
