### ISSUE TITLE
Cut and push a new release

### ISSUE THREAD

**Issue by michaelklishin** [michaelklishin/quartz-mongodb#87]

**Comment by jochenberger** [comment]
Any news on this one? I'd love to see a release that includes #85, #86. and #89.

**Comment by michaelklishin** [comment]
Need to wait for some more changes from @pwojnowski and then we can release 2.0.

**Comment by pwojnowski** [comment]
Shall this release still support Java 6?

**Comment by michaelklishin** [comment]
@pwojnowski no, now is a good time to drop JDK 6 support.

**Comment by pwojnowski** [comment]
Just one more question. In QueryHelper.matchingKeysConditionFor() "case ENDS_WITH" doesn't have "break" and falls through to "case CONTAINS". Was that on purpose?

**Comment by michaelklishin** [comment]
@pwojnowski no, definitely not. I suspect this came unnoticed because "endsWith" is the least frequently used matcher :)

**Comment by pwojnowski** [comment]
That's all from my side at this moment. IMHO you can do the release and other changes (if any) will go into the next (possibly minor/bugfix) release.

**Comment by michaelklishin** [comment]
@pwojnowski thank you, will do!

**Comment by michaelklishin** [comment]
I'm going to cut a new release in the next couple of days. Sorry for the delay.

**Comment by slawomirsepiol** [comment]
Hi. I found bug in the current code - every method that is supposed to pause or resume multiple triggers, actually changes state of only one. I fixed that and submitted a pull request - could you include it in the release?

**Comment by michaelklishin** [comment]
@slawomirsepiol sure, thank you!

**Comment by michaelklishin** [comment]
There were quite a few changes so I decided to release `2.0.0-rc1` first. Please give it a try.
