### ISSUE TITLE
Not able to get quartz-mongodb working

### ISSUE THREAD

**Issue by Gopinathp** [michaelklishin/quartz-mongodb#88]
Sorry for my stupidity, I am a newbie with spring/quartz/mongodb. I need some sample project which shows how to use quartz-mongodb.

**Comment by michaelklishin** [comment]
I don't have one and don't have any time to develop one.

Quartz has a [documentation guide on JobStores](http://quartz-scheduler.org/documentation/quartz-2.1.x/tutorials/tutorial-lesson-09). This project has a README with configuration examples. There isn't much else to cover.
