### ISSUE TITLE
Please implement `storeJobsAndTriggers(Map<JobDetail, List<Trigger>> triggersAndJobs, boolean replace)`

### ISSUE THREAD

**Issue by Gitward** [michaelklishin/quartz-mongodb#91]
I realized, that the method `public void storeJobsAndTriggers(Map<JobDetail, List<Trigger>> triggersAndJobs, boolean replace)` is not implemented (https://github.com/michaelklishin/quartz-mongodb/blob/master/src/main/java/com/novemberain/quartz/mongodb/MongoDBJobStore.java#L163) . Is there a special reason for that?

**Comment by michaelklishin** [comment]
@Gitward no, no particular reason for not implementing it.

I don't actively work on this library. Feel free to submit a pull request.

**Comment by michaelklishin** [comment]
It is implemented now as far as I can see. So give `2.0.0` a try.

**Comment by jochenberger** [comment]
No, it isn't: 
https://github.com/michaelklishin/quartz-mongodb/blob/2.0.0/src/main/java/com/novemberain/quartz/mongodb/MongoDBJobStore.java#L195

**Comment by pwojnowski** [comment]
This one should be easy to implement. :-)
