### ISSUE TITLE
Upgrade to MongoDB Java driver 3.x

### ISSUE THREAD

**Issue by netvl** [michaelklishin/quartz-mongodb#95]
Currently quartz-mongodb can't be used in environments where 3.x Java driver is used. It leads to weird class initialization errors due to class versions mismatch.

Are there plans to upgrade quartz-mongodb to use more recent version of Java driver?

**Comment by michaelklishin** [comment]
@netvl I'd accept a pull request that upgrades the client.

**Comment by sclausen** [comment]
I would really like to participate, but unfortunately the project setup is clojure, so I'm drawing a blank on that one.
If it only had been maven…

**Comment by pwojnowski** [comment]
After upgrade Client should work only with Mongo 3.x or rather with 3.x and 2.x?

**Comment by sclausen** [comment]
I used the new mongo driver with 2.4, 2.6 and 3.0, so it could basically workd, but I don't know this project enough which changes have to be made to get this to work. As I wrote, a project setup with clojure is not my field.

**Comment by michaelklishin** [comment]
@sclausen all you have to do is to install Leiningen and run `lein test`. Not any different from Maven.

**Comment by sclausen** [comment]
Yeah, it didn't worked very well with leiningen for me. Maybe I was a bit imatient and invested too little time. I'll go and start a second try tomorrow ;)

**Comment by michaelklishin** [comment]
@pwojnowski [this compatibility table](http://docs.mongodb.org/manual/release-notes/3.0-compatibility/#driver-compatibility-changes) is the best I could find. Java driver 2.13 supports MongoDB 2.6 and 3.0. I'd expect 3.0 to mostly work with the 2.6 server.

**Comment by pwojnowski** [comment]
Hi.
I already did most of the work here: https://github.com/pwojnowski/quartz-mongodb
I still have one test to fix (units-test/test-aquire-next-trigger), but if you (@sclausen) haven't started the work then maybe it would be just faster to find out why the test fails than doing everything from scratch.

**Comment by michaelklishin** [comment]
@pwojnowski thank you!

**Comment by sclausen** [comment]
@pwojnowski wow! thank you!

**Comment by pwojnowski** [comment]
I fixed that. I don't know whether everything is ok, but at least all tests pass.
If you are ok with that I can create a pull request.

**Comment by michaelklishin** [comment]
@pwojnowski please do!

**Comment by pwojnowski** [comment]
IMHO quartz-mongo code (in general) cries for refactorings to increase readability.
Moreover there are still couple of changes that should be done: close cursors, use builders from API 3, etc. If you are open to such changes I can do them and create another pull request.

**Comment by michaelklishin** [comment]
@pwojnowski no objections from me, thanks.

**Comment by michaelklishin** [comment]
Resolved in master thanks to @pwojnowski.
