### ISSUE TITLE
Getting following error 

### ISSUE THREAD

**Issue by arpitrajpurohit12** [michaelklishin/quartz-mongodb#96]
I have set the properties as mentioned . But I am getting following error:

JobStore class 'com.novemberain.quartz.mongodb.MongoDBJobStore' props could not be configured.Exception in thread "main" java.lang.NullPointerException

**Comment by michaelklishin** [comment]
I cannot suggest anything from this 2 line trace. I have poor telepathic skills, so please post  `quartz.properties` and stack trace next time.

**Comment by arpitrajpurohit12** [comment]
Sorry for the incomplete info-

Following is quartz.properties :

# Use the MongoDB store
org.quartz.jobStore.class=com.novemberain.quartz.mongodb.MongoDBJobStore
# MongoDB URI (optional if 'org.quartz.jobStore.addresses' is set)
org.quartz.jobStore.mongoUri=mongodb://localhost:27020
# database name
org.quartz.jobStore.dbName=quartz
# Will be used to create collections like mycol_jobs, mycol_triggers, mycol_calendars, mycol_locks
org.quartz.jobStore.collectionPrefix=mycol
# thread count setting is ignored by the MongoDB store but Quartz requries it
org.quartz.threadPool.threadCount=1
org.quartz.jobStore.isClustered = false

Following error I get :

JobStore class 'com.novemberain.quartz.mongodb.MongoDBJobStore' props could not be configured.Exception in thread "main" java.lang.NullPointerException. 

"Its from line 883 of StdSchedulerFactory"

Following is the constructor : 

    public CScheduler() throws SchedulerException{
        properties=new Properties();

        InputStream stream= getClass().getClassLoader().getResourceAsStream(propertiesFile);
        try{
            properties.load(stream);
        }
        catch(Exception e)
        {
            System.out.println("Exception:"+e);
        }
       SchedulerFactory sf = new StdSchedulerFactory(properties);
       this.scheduler=sf.getScheduler();
    }

      
.
