### ISSUE TITLE
Following error showing up

### ISSUE THREAD

**Issue by arpitrajpurohit12** [michaelklishin/quartz-mongodb#98]
Sorry for the incomplete info in the previous question asked-

Following is quartz.properties :

org.quartz.jobStore.class=com.novemberain.quartz.mongodb.MongoDBJobStore
org.quartz.jobStore.mongoUri=mongodb://localhost:27020
org.quartz.jobStore.dbName=quartz
org.quartz.jobStore.collectionPrefix=mycol
org.quartz.threadPool.threadCount=1
org.quartz.jobStore.isClustered = false

Following error I get :

JobStore class 'com.novemberain.quartz.mongodb.MongoDBJobStore' props could not be configured.Exception in thread "main" java.lang.NullPointerException.

"Its from line 883 of StdSchedulerFactory"

Following is the constructor :

public CScheduler() throws SchedulerException{
        properties=new Properties();
        InputStream stream= getClass().getClassLoader().getResourceAsStream(propertiesFile);
    try{
        properties.load(stream);
    }
    catch(Exception e)
    {
        System.out.println("Exception:"+e);
    }
     SchedulerFactory sf = new StdSchedulerFactory(properties);
     this.scheduler=sf.getScheduler();
  }

**Comment by michaelklishin** [comment]
The exception comes from Quartz itself. This strongly suggests a misconfiguration.
